### ISSUE TITLE
[HELP]CANNOT INSTALL WITH PythonError！

### ISSUE THREAD

**Issue by jukrb0x** [abaykan/53R3N17Y#6]
**The error appears in the step.**

My Macbook is brand new. MBP with Mac OS 10.13.4.
```
USERNAME:serenity USER$ pip install -r requirements.txt
Collecting colorama (from -r requirements.txt (line 1))
  Using cached colorama-0.3.9-py2.py3-none-any.whl
Collecting requests (from -r requirements.txt (line 2))
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->-r requirements.txt (line 2))
  Using cached certifi-2018.1.18-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->-r requirements.txt (line 2))
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests->-r requirements.txt (line 2))
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests->-r requirements.txt (line 2))
  Using cached urllib3-1.22-py2.py3-none-any.whl
Installing collected packages: colorama, certifi, chardet, idna, urllib3, requests
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.3-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.3-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.3-py2.7.egg/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip-9.0.3-py2.7.egg/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip-9.0.3-py2.7.egg/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip-9.0.3-py2.7.egg/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip-9.0.3-py2.7.egg/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip-9.0.3-py2.7.egg/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/colorama-0.3.9.dist-info'
```

I don't know what happened. Plz help.

**Comment by abaykan** [comment]
Try `sudo pip install -r requirements.txt`

**Comment by fabaff** [comment]
Instead of `sudo` it's better use `pip` with `--user` or create a [`venv`](https://docs.python.org/3.6/library/venv.html). This way you don't interfere with the packages installed by your distribution's package management tool.

**Comment by jukrb0x** [comment]
Succeed! THANK U GUYS.
